import React, { useState } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  Platform,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { useAppStore } from '../../store/routineStore';
import { colors, spacing, typography, radius } from '../../theme';

// ---------------------------------------------------------------------------
// HTML report builder
// ---------------------------------------------------------------------------

function buildHtml(
  childName: string,
  avatarEmoji: string,
  dateRange: string,
  sections: ReportSection[]
): string {
  const sectionHtml = sections.map((s) => `
    <div class="section">
      <h2>${s.emoji} ${s.title}</h2>
      ${s.html}
    </div>
  `).join('');

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<style>
  body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1A1A2E; margin: 0; padding: 40px; background: #F8F7FF; }
  .header { display: flex; align-items: center; margin-bottom: 32px; padding-bottom: 24px; border-bottom: 2px solid #E0DDF5; }
  .avatar { font-size: 64px; margin-right: 24px; }
  .header-text h1 { margin: 0 0 4px; font-size: 28px; color: #5B4FCF; }
  .header-text p { margin: 0; font-size: 14px; color: #6B6B8D; }
  .section { background: #fff; border-radius: 12px; padding: 20px; margin-bottom: 16px; box-shadow: 0 2px 8px rgba(0,0,0,0.06); }
  .section h2 { margin: 0 0 16px; font-size: 18px; color: #1A1A2E; }
  table { width: 100%; border-collapse: collapse; }
  th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #6B6B8D; padding: 8px 0; border-bottom: 1px solid #E0DDF5; }
  td { font-size: 14px; padding: 10px 0; border-bottom: 1px solid #F0EFF8; color: #1A1A2E; }
  .stat-row { display: flex; gap: 16px; flex-wrap: wrap; }
  .stat { flex: 1; min-width: 80px; text-align: center; background: #F8F7FF; border-radius: 8px; padding: 12px; }
  .stat-value { font-size: 28px; font-weight: 700; color: #5B4FCF; }
  .stat-label { font-size: 11px; color: #6B6B8D; margin-top: 4px; }
  .badge { display: inline-block; background: #E0DDF5; border-radius: 99px; padding: 3px 10px; font-size: 12px; color: #5B4FCF; margin: 2px; }
  .badge-positive { background: #E8F5E9; color: #2E7D32; }
  .badge-concern { background: #FFF8E1; color: #F57F17; }
  .empty { color: #A0A0B8; font-style: italic; font-size: 14px; }
  .footer { margin-top: 32px; text-align: center; font-size: 11px; color: #A0A0B8; }
</style>
</head>
<body>
  <div class="header">
    <div class="avatar">${avatarEmoji}</div>
    <div class="header-text">
      <h1>${childName}'s Progress Report</h1>
      <p>Generated by Spicey Brain &nbsp;·&nbsp; ${dateRange}</p>
    </div>
  </div>
  ${sectionHtml}
  <div class="footer">Spicey Brain — ADHD Routine Companion &nbsp;·&nbsp; Confidential</div>
</body>
</html>`;
}

interface ReportSection {
  emoji: string;
  title: string;
  html: string;
}

// ---------------------------------------------------------------------------
// Section builders
// ---------------------------------------------------------------------------

function routineSection(sessions: any[], routines: any[]): ReportSection {
  const completed = sessions.filter((s) => !!s.completedAt);
  const rate = sessions.length > 0 ? Math.round((completed.length / sessions.length) * 100) : 0;

  const byRoutine: Record<string, { name: string; completions: number }> = {};
  for (const s of completed) {
    const r = routines.find((r: any) => r.id === s.routineId);
    if (r) {
      byRoutine[r.id] = byRoutine[r.id] ?? { name: r.name, completions: 0 };
      byRoutine[r.id].completions++;
    }
  }
  const rows = Object.values(byRoutine)
    .sort((a, b) => b.completions - a.completions)
    .map((r) => `<tr><td>${r.name}</td><td>${r.completions} times</td></tr>`)
    .join('');

  return {
    emoji: '📋',
    title: 'Routines',
    html: `
      <div class="stat-row">
        <div class="stat"><div class="stat-value">${completed.length}</div><div class="stat-label">Completed</div></div>
        <div class="stat"><div class="stat-value">${rate}%</div><div class="stat-label">Completion rate</div></div>
        <div class="stat"><div class="stat-value">${completed.reduce((a, s) => a + s.taskCompletions.length + 5, 0)}</div><div class="stat-label">Stars earned</div></div>
      </div>
      ${rows ? `<table style="margin-top:16px"><tr><th>Routine</th><th>Completions</th></tr>${rows}</table>` : ''}
    `,
  };
}

function moodSection(entries: any[]): ReportSection {
  if (entries.length === 0) {
    return { emoji: '😊', title: 'Mood & Behavior', html: '<p class="empty">No mood entries recorded.</p>' };
  }

  const avgMood = (entries.reduce((s, e) => s + e.mood, 0) / entries.length).toFixed(1);
  const avgFocus = (entries.reduce((s, e) => s + e.focus, 0) / entries.length).toFixed(1);
  const moodEmojis = ['', '😔', '😕', '😐', '🙂', '😄'];
  const focusEmojis = ['', '🌀', '😵', '😶', '🎯', '⚡'];

  const behaviorCounts: Record<string, number> = {};
  entries.forEach((e) =>
    e.behaviors.forEach((b: string) => { behaviorCounts[b] = (behaviorCounts[b] ?? 0) + 1; })
  );
  const sortedBehaviors = Object.entries(behaviorCounts).sort((a, b) => b[1] - a[1]);
  const behaviorBadges = sortedBehaviors
    .map(([b, n]) => `<span class="badge">${b} × ${n}</span>`)
    .join(' ');

  const recent = entries
    .slice(0, 7)
    .map((e) => `<tr><td>${new Date(e.recordedAt).toLocaleDateString()}</td><td>${moodEmojis[e.mood]} ${e.mood}/5</td><td>${focusEmojis[e.focus]} ${e.focus}/5</td><td>${e.behaviors.join(', ') || '—'}</td></tr>`)
    .join('');

  return {
    emoji: '😊',
    title: 'Mood & Behavior',
    html: `
      <div class="stat-row">
        <div class="stat"><div class="stat-value">${entries.length}</div><div class="stat-label">Entries</div></div>
        <div class="stat"><div class="stat-value">${avgMood}/5</div><div class="stat-label">Avg Mood</div></div>
        <div class="stat"><div class="stat-value">${avgFocus}/5</div><div class="stat-label">Avg Focus</div></div>
      </div>
      ${behaviorBadges ? `<div style="margin-top:16px"><strong style="font-size:12px;color:#6B6B8D">Observed behaviors</strong><div style="margin-top:8px">${behaviorBadges}</div></div>` : ''}
      <table style="margin-top:16px">
        <tr><th>Date</th><th>Mood</th><th>Focus</th><th>Behaviors</th></tr>
        ${recent}
      </table>
    `,
  };
}

function medicationSection(medications: any[]): ReportSection {
  if (medications.length === 0) {
    return { emoji: '💊', title: 'Medication', html: '<p class="empty">No medications recorded.</p>' };
  }

  const rows = medications.map((med) => {
    const totalLogs = med.logHistory.length;
    const takenLogs = med.logHistory.filter((l: any) => !l.skipped).length;
    const adherence = totalLogs > 0 ? Math.round((takenLogs / totalLogs) * 100) : 0;
    return `<tr>
      <td><strong>${med.name}</strong>${med.dosage ? ` — ${med.dosage}` : ''}</td>
      <td>${med.times.join(', ')}</td>
      <td>${totalLogs > 0 ? `${adherence}% (${takenLogs}/${totalLogs})` : 'No logs yet'}</td>
    </tr>`;
  }).join('');

  return {
    emoji: '💊',
    title: 'Medication',
    html: `<table><tr><th>Medication</th><th>Times</th><th>Adherence</th></tr>${rows}</table>`,
  };
}

function teacherSection(notes: any[], contacts: any[]): ReportSection {
  if (notes.length === 0) {
    return { emoji: '👩‍🏫', title: 'Teacher Notes', html: '<p class="empty">No teacher notes recorded.</p>' };
  }

  const positives = notes.filter((n) => n.type === 'positive').length;
  const concerns = notes.filter((n) => n.type === 'concern').length;

  const rows = notes.slice(0, 10).map((n) => {
    const contact = contacts.find((c: any) => c.id === n.teacherContactId);
    const typeClass = n.type === 'positive' ? 'badge-positive' : n.type === 'concern' ? 'badge-concern' : '';
    return `<tr>
      <td>${new Date(n.date).toLocaleDateString()}</td>
      <td><span class="badge ${typeClass}">${n.type}</span></td>
      <td>${contact?.name ?? 'General'}</td>
      <td>${n.content}</td>
    </tr>`;
  }).join('');

  return {
    emoji: '👩‍🏫',
    title: 'Teacher Notes',
    html: `
      <div class="stat-row">
        <div class="stat"><div class="stat-value">${notes.length}</div><div class="stat-label">Total notes</div></div>
        <div class="stat"><div class="stat-value">${positives}</div><div class="stat-label">Positives</div></div>
        <div class="stat"><div class="stat-value">${concerns}</div><div class="stat-label">Concerns</div></div>
      </div>
      <table style="margin-top:16px"><tr><th>Date</th><th>Type</th><th>From</th><th>Note</th></tr>${rows}</table>
    `,
  };
}

// ---------------------------------------------------------------------------
// Screen
// ---------------------------------------------------------------------------

type RangeOption = '7d' | '30d' | '90d' | 'all';

export default function ReportScreen() {
  const { parentProfile, moodEntries, sessions, routines, medications, teacherContacts, teacherNotes } =
    useAppStore();

  const children = parentProfile?.childProfiles ?? [];
  const [selectedChildId, setSelectedChildId] = useState(children[0]?.id ?? '');
  const [range, setRange] = useState<RangeOption>('30d');
  const [exporting, setExporting] = useState(false);

  const selectedChild = children.find((c) => c.id === selectedChildId);

  const cutoff = (): Date => {
    const d = new Date();
    if (range === '7d') d.setDate(d.getDate() - 7);
    else if (range === '30d') d.setDate(d.getDate() - 30);
    else if (range === '90d') d.setDate(d.getDate() - 90);
    else d.setFullYear(2000);
    return d;
  };

  const filter = <T extends { [k: string]: any }>(arr: T[], dateKey: string) =>
    arr.filter((x) => x.childProfileId === selectedChildId && new Date(x[dateKey]) >= cutoff());

  const childSessions = sessions.filter(
    (s) => s.childProfileId === selectedChildId && new Date(s.startedAt) >= cutoff()
  );
  const childMoods = filter(moodEntries, 'recordedAt');
  const childMeds = medications.filter((m) => m.childProfileId === selectedChildId);
  const childNotes = filter(teacherNotes, 'date');
  const childContacts = teacherContacts.filter((c) => c.childProfileId === selectedChildId);

  const rangeLabel = () => {
    const now = new Date();
    const from = cutoff();
    if (range === 'all') return 'All time';
    return `${from.toLocaleDateString()} – ${now.toLocaleDateString()}`;
  };

  const handleExport = async () => {
    if (!selectedChild) return;
    setExporting(true);
    try {
      const sections: ReportSection[] = [
        routineSection(childSessions, routines),
        moodSection(childMoods),
        medicationSection(childMeds),
        teacherSection(childNotes, childContacts),
      ];
      const html = buildHtml(selectedChild.name, selectedChild.avatarEmoji, rangeLabel(), sections);
      const { uri } = await Print.printToFileAsync({ html, base64: false });

      const canShare = await Sharing.isAvailableAsync();
      if (canShare) {
        await Sharing.shareAsync(uri, {
          mimeType: 'application/pdf',
          dialogTitle: `${selectedChild.name}'s Progress Report`,
          UTI: 'com.adobe.pdf',
        });
      } else {
        Alert.alert('PDF saved', `Report saved to: ${uri}`);
      }
    } catch (e: any) {
      Alert.alert('Export failed', e.message ?? 'Unknown error');
    } finally {
      setExporting(false);
    }
  };

  const RANGES: { label: string; value: RangeOption }[] = [
    { label: '7 days', value: '7d' },
    { label: '30 days', value: '30d' },
    { label: '90 days', value: '90d' },
    { label: 'All time', value: 'all' },
  ];

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
        <Text style={styles.screenTitle}>Export Report</Text>
        <Text style={styles.subtitle}>
          Generate a PDF progress report to share with doctors, therapists, or schools
        </Text>

        {/* Child selector */}
        {children.length > 1 && (
          <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.childSelector}>
            {children.map((child) => (
              <TouchableOpacity
                key={child.id}
                style={[styles.childChip, selectedChildId === child.id && styles.childChipActive]}
                onPress={() => setSelectedChildId(child.id)}
              >
                <Text>{child.avatarEmoji}</Text>
                <Text style={[styles.chipName, selectedChildId === child.id && styles.chipNameActive]}>
                  {child.name}
                </Text>
              </TouchableOpacity>
            ))}
          </ScrollView>
        )}

        {/* Date range */}
        <View style={styles.field}>
          <Text style={styles.label}>Date Range</Text>
          <View style={styles.rangeRow}>
            {RANGES.map((r) => (
              <TouchableOpacity
                key={r.value}
                style={[styles.rangeChip, range === r.value && styles.rangeChipActive]}
                onPress={() => setRange(r.value)}
              >
                <Text style={[styles.rangeChipText, range === r.value && styles.rangeChipTextActive]}>
                  {r.label}
                </Text>
              </TouchableOpacity>
            ))}
          </View>
        </View>

        {/* Report preview */}
        <View style={styles.previewCard}>
          <Text style={styles.previewTitle}>Report will include</Text>
          {[
            { emoji: '📋', label: 'Routines', count: `${childSessions.filter((s) => !!s.completedAt).length} completions` },
            { emoji: '😊', label: 'Mood & Behavior', count: `${childMoods.length} entries` },
            { emoji: '💊', label: 'Medication', count: `${childMeds.length} medications` },
            { emoji: '👩‍🏫', label: 'Teacher Notes', count: `${childNotes.length} notes` },
          ].map((item) => (
            <View key={item.emoji} style={styles.previewRow}>
              <Text style={styles.previewEmoji}>{item.emoji}</Text>
              <Text style={styles.previewLabel}>{item.label}</Text>
              <Text style={styles.previewCount}>{item.count}</Text>
            </View>
          ))}
          <Text style={styles.previewRange}>Period: {rangeLabel()}</Text>
        </View>

        <TouchableOpacity
          style={[styles.exportBtn, exporting && styles.exportBtnLoading]}
          onPress={handleExport}
          disabled={exporting}
        >
          {exporting ? (
            <ActivityIndicator color="#fff" />
          ) : (
            <Text style={styles.exportBtnText}>📄 Export PDF Report</Text>
          )}
        </TouchableOpacity>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  scroll: { padding: spacing.md, paddingBottom: spacing.xxl },
  screenTitle: { fontSize: typography.fontSizeXXL, fontWeight: typography.fontWeightBold, color: colors.textPrimary, marginBottom: spacing.xs },
  subtitle: { fontSize: typography.fontSizeSM, color: colors.textSecondary, marginBottom: spacing.lg, lineHeight: 20 },
  childSelector: { marginBottom: spacing.lg },
  childChip: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderRadius: radius.full, borderWidth: 1, borderColor: colors.border, paddingVertical: spacing.xs, paddingHorizontal: spacing.md, marginRight: spacing.sm, gap: spacing.xs },
  childChipActive: { backgroundColor: colors.primaryLight, borderColor: colors.primary },
  chipName: { fontSize: typography.fontSizeSM, color: colors.textSecondary, fontWeight: typography.fontWeightMedium },
  chipNameActive: { color: '#fff' },
  field: { marginBottom: spacing.lg },
  label: { fontSize: typography.fontSizeMD, fontWeight: typography.fontWeightSemiBold, color: colors.textPrimary, marginBottom: spacing.sm },
  rangeRow: { flexDirection: 'row', gap: spacing.sm },
  rangeChip: { flex: 1, backgroundColor: colors.surface, borderRadius: radius.md, borderWidth: 1, borderColor: colors.border, paddingVertical: spacing.sm, alignItems: 'center' },
  rangeChipActive: { backgroundColor: colors.primaryLight, borderColor: colors.primary },
  rangeChipText: { fontSize: typography.fontSizeSM, color: colors.textSecondary, fontWeight: typography.fontWeightMedium },
  rangeChipTextActive: { color: '#fff' },
  previewCard: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    padding: spacing.md,
    marginBottom: spacing.lg,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  previewTitle: { fontSize: typography.fontSizeSM, fontWeight: typography.fontWeightSemiBold, color: colors.textSecondary, marginBottom: spacing.md },
  previewRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: spacing.xs, gap: spacing.sm },
  previewEmoji: { fontSize: 20, width: 28 },
  previewLabel: { flex: 1, fontSize: typography.fontSizeMD, color: colors.textPrimary },
  previewCount: { fontSize: typography.fontSizeSM, color: colors.primary, fontWeight: typography.fontWeightMedium },
  previewRange: { fontSize: typography.fontSizeXS, color: colors.textMuted, marginTop: spacing.md, textAlign: 'center' },
  exportBtn: {
    backgroundColor: colors.primary,
    borderRadius: radius.xl,
    paddingVertical: spacing.md,
    alignItems: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 6,
  },
  exportBtnLoading: { opacity: 0.7 },
  exportBtnText: { fontSize: typography.fontSizeLG, fontWeight: typography.fontWeightBold, color: '#fff' },
});
